# Generated by Django 6.0.6 on 2026-06-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='available',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unavailable_message',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unavailable_reason',
        ),
    ]
